### PR TITLE
Fixed opcode highlights

### PR DESCRIPTION
**Pull request by cassiebeckley**
Added `IAQ` and replaced `HWG` with `HWQ`.

They were probably just omissions/typos from my last pull request.

### CODE REVIEW

**Comment by mappum** [comment]
It doesn't look like you committed it.

**Comment by cassiebeckley** [comment]
Urgh, sorry about that. NOW it's fixed.

**Comment by mappum** [comment]
Haha no problem, thanks.

**Comment by mappum** [comment]
You seem like you're doing a lot of stuff for 0x10code :D. If you ever need to talk, I hang out in #0x10c-dev on Freenode.

**Pull request merged**
