### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by jsanders**
Fixes my only frustration with 0x10co.de - I can only ever browse the top and most recent 25 programs of all time!

Adds pagination for /top and /forks/:id, but not for the sidebar of recent programs.

Very willing to work on any code or UI style criticisms you may have!

### CODE REVIEW

**Comment by mappum** [comment]
I'll test this out, and maybe pull it in a few minutes. Thanks!

**Comment by mappum** [comment]
I can't figure out where you control the current page, did you not add links to page numbers?

**Comment by mappum** [comment]
Nevermind, I pulled the wrong branch. However, you changes error:
`node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object function (obj){
  utils.merge(this._locals, obj);
  return this;
} has no method 'use'
    at Object.<anonymous> (/home/mappum/test/0x10code/app.js:28:12)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)
`

**Comment by jsanders** [comment]
@mappum Wow, Didn't expect you to respond so quickly! Looks like you and I are on different versions of express. When I followed the express-pagination instructions to add the `paginate` function to `app.helpers` it blew up for me and I ended up finding instructions about migrating from 2.x to 3.x at https://github.com/visionmedia/express/wiki/Migrating-from-2.x-to-3.x which has a section about helpers. I'll be glad to change it if you think that's the right thing.

**Comment by jsanders** [comment]
Whoops, wrong button.

**Comment by mappum** [comment]
Well I just installed the latest version of express for your code (or whatever installs when you don't specify a version). If you can get it to work with that, I'll pull it.

**Comment by jsanders** [comment]
Here is my output from `npm list`, for which it is working quite nicely:

```
0x10code@0.0.1 /Users/james/Code/dcpu16/0x10code
├─┬ express@3.0.0alpha1 
│ ├── commander@0.5.2 
│ ├─┬ connect@2.1.2 
│ │ ├── crc@0.1.0 
│ │ ├── formidable@1.0.9 
│ │ ├── mime@1.2.4 
│ │ └── qs@0.4.2 
│ ├── debug@0.6.0 
│ ├── mime@1.2.5 
│ └── mkdirp@0.3.1 
├── express-pagination@0.0.5 
├─┬ jade@0.24.0 
│ ├── commander@0.5.2 
│ └── mkdirp@0.3.0 
├── markdown@0.3.1 
├── moment@1.5.1 
├─┬ mongoose@2.5.14 
│ ├── hooks@0.2.0 
│ └─┬ mongodb@0.9.9-7 
│   └── bson@0.0.4 
└── node-markdown@0.1.0
```

Let me know if you run into any problems after upgrading, or if you want me to downgrade my version and get it to work.

**Comment by mappum** [comment]
Looks like mine is on express 2.5.9, and that's what installs by default, so I'll stick with that. Is the only difference that needs to be made the `.helper`?

**Comment by jsanders** [comment]
Hmm, I just did `npm install` and I ended up with 3.0.0alpha1. I don't really know enough about npm to figure our the discrepancy, but I'll figure out how to downgrade mine and make it work with 2.5.9.

**Comment by mappum** [comment]
I'm not sure whether or not I should upgrade or you should downgrade. If you need to specify a version, put it in the dependencies in the package.json (`"express": "2.5.9"`).

**Comment by jsanders** [comment]
Ok, this should be working with 2.5.9 now!

**Comment by mappum** [comment]
Awesome, it works. Do you think you could pull my current repo so I can pull it? Thanks!

**Comment by jsanders** [comment]
Ok I rebased off of your current master, so you should be able to merge now!

**Comment by mappum** [comment]
Awesome! Thank you!

**Comment by mappum** [comment]
Huh, closing it doesnt let me pull it automitcally :/

**Comment by jsanders** [comment]
Huh, not sure what I did wrong, but it looks like you managed to get it in anyway! Played around with it on the site, seems to be working great - thanks!

**Pull request merged**
