### PR TITLE
Add the ability to browse recent programs

### PR DESCRIPTION
**Pull request by jsanders**
Add "Recent Programs" to the nav bar, add "More" link to the sidebar,
which takes you to page two of the Recent Programs list view.

### CODE REVIEW

**Comment by jsanders** [comment]
/ping @mappum - Any interest in this functionality?

**Comment by mappum** [comment]
Oh right, I read is but thought it would come in the other request. When it wasn't there I was confused. Thanks, testing now.

**Comment by jsanders** [comment]
Yeah sorry, I just did it as two different chunks of functionality.

**Comment by jsanders** [comment]
This keeps showing my "Your Pull Requests" thingie and I doubt there's any point in merging it :crying_cat_face:, so I'm closing!

**Pull request closed without merging**
